name: boycott_pro
description: A new Flutter project.

publish_to: "none"

version: 1.0.2+2

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0

  cupertino_icons: ^1.0.2
  camera: ^0.10.5+5
  google_mlkit_text_recognition: ^0.10.0
  permission_handler: ^11.0.1
  lottie: ^2.6.0
  flutter_animate: ^4.2.0+1

  get: ^4.6.5
  in_app_update: ^4.2.2

  firebase_core: ^2.19.0
  cloud_firestore: ^4.12.0
  firebase_remote_config: ^4.3.1
  firebase_admob_config: ^1.3.1
  google_mobile_ads: ^3.1.0
  firebase_messaging: ^14.7.1
  flutter_local_notifications: ^16.1.0

  http: ^1.1.0
  sizer: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

flutter_assets:
  assets_path: assets/
  output_path: lib/generated/assets/
  filename: assets.dart
flutter_intl:
  enabled: true
