// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXy3omu7BJj2Ie9mj3oIUKhJo-mjlaWos',
    appId: '1:153049795520:web:5c7b70e05dbc071bba5625',
    messagingSenderId: '740164993241',
    projectId: 'unknown-number-whats-message',
    authDomain: 'guard-master-2e8fe.firebaseapp.com',
    storageBucket: 'unknown-number-whats-message.appspot.com',
    measurementId: 'G-JBFEBMSWB7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2JaZetvs-D3HIXm5yu5XyF6At-tEUe78',
    appId: '1:740164993241:android:597140b8296f7320017ec8',
    messagingSenderId: '740164993241',
    projectId: 'unknown-number-whats-message',
    storageBucket: 'unknown-number-whats-message.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:740164993241:ios:edfb84e20ff04241017ec8',
    messagingSenderId: '740164993241',
    projectId: 'unknown-number-whats-message',
    storageBucket: 'unknown-number-whats-message.appspot.com',
    iosClientId: '',
    iosBundleId: 'com.devmnem.boycottPro',
  );
}
